import config from '../config/index.js';

// ... (existing helper functions)

/**
 * Convert snake_case to camelCase
 * @param {string} str - Snake case string
 * @returns {string} Camel case string
 */
const snakeToCamel = (str) => {
  return str.replace(/_([a-z])/g, (match, letter) => letter.toUpperCase());
};

/**
 * Recursively transform object keys from snake_case to camelCase
 * @param {Object|Array} obj - Object or array to transform
 * @returns {Object|Array} Transformed object/array
 */
const transformKeys = (obj) => {
  if (Array.isArray(obj)) {
    return obj.map(item => transformKeys(item));
  }

  if (obj !== null && typeof obj === 'object' && !(obj instanceof Date)) {
    return Object.keys(obj).reduce((acc, key) => {
      const camelKey = snakeToCamel(key);
      acc[camelKey] = transformKeys(obj[key]);
      return acc;
    }, {});
  }

  return obj;
};

const transformSong = (song) => {
  if (!song) return null;

  let downloadUrl = song.download_url || null;

  // If no explicit download URL but public R2 is configured and we have an ID
  if (!downloadUrl && config.r2.publicUrl && song.r2_key) {
    // Check if r2_key is a direct file or a directory (HLS)
    const isDirectFile = /\.(mp3|m4a|wav|flac|ogg)$/i.test(song.r2_key);

    if (isDirectFile) {
      downloadUrl = `${config.r2.publicUrl}/${song.r2_key}`;
    } else {
      // For HLS folders (e.g. songs/00fe084b-9f8c-4aad-988f-44b70725ca3f/master.m3u8),
      // we default to master.m3u8, but fallback to high.m3u8 if that fails/doesn't exist logic 
      // is usually handled by the player or we point to master.
      // Based on existing logic in stream.controller.js, we assume master.m3u8 is the entry point.
      // However, if the user only has specific qualities, we might need a more robust check later.
      // For now, consistent with stream controller:
      downloadUrl = `${config.r2.publicUrl}/${song.r2_key.endsWith('/') ? song.r2_key : song.r2_key + '/'}master.m3u8`;
    }
  }

  return {
    id: song.id,
    title: song.title,
    artist: song.artist,
    album: song.album,
    albumArtUrl: song.album_art_url || song.albumArtUrl || null,
    durationMs: song.duration_ms,
    r2Key: song.r2_key,
    fileSizes: song.file_sizes || {},
    playCount: song.play_count || 0,
    lastUpdated: song.last_updated,
    popularityScore: song.popularity_score || 0,
    createdAt: song.created_at,
    updatedAt: song.updated_at,
    downloadUrl: downloadUrl,
  };
};

/**
 * Transform Playlist model from database to frontend format
 * @param {Object} playlist - Playlist from database
 * @returns {Object} Transformed playlist
 */
const transformPlaylist = (playlist) => {
  if (!playlist) return null;

  return {
    id: playlist.id,
    name: playlist.name,
    description: playlist.description || null,
    userId: playlist.user_id,
    songIds: playlist.song_ids || [],
    autoGenerated: playlist.auto_generated || false,
    isPublic: playlist.is_public || false,
    createdAt: playlist.created_at,
    updatedAt: playlist.updated_at,
  };
};

/**
 * Transform User model from database to frontend format
 * @param {Object} user - User from database
 * @returns {Object} Transformed user
 */
const transformUser = (user) => {
  if (!user) return null;

  return {
    id: user.id,
    email: user.email,
    username: user.username || null,
    profileImageUrl: user.profile_image_url || null,
    createdAt: user.created_at,
    updatedAt: user.updated_at,
  };
};

/**
 * Transform User Preferences model from database to frontend format
 * @param {Object} prefs - User preferences from database
 * @returns {Object} Transformed preferences
 */
const transformUserPreferences = (prefs) => {
  if (!prefs) return null;

  return {
    userId: prefs.user_id,
    preferredQuality: prefs.preferred_quality || 'high',
    autoDownload: prefs.auto_download || false,
    downloadQuality: prefs.download_quality || 'medium',
    dataSaverMode: prefs.data_saver_mode || false,
    theme: prefs.theme || 'dark',
    createdAt: prefs.created_at,
    updatedAt: prefs.updated_at,
  };
};

/**
 * Transform User Interaction model from database to frontend format
 * @param {Object} interaction - User interaction from database
 * @returns {Object} Transformed interaction
 */
const transformUserInteraction = (interaction) => {
  if (!interaction) return null;

  return {
    id: interaction.id,
    userId: interaction.user_id,
    songId: interaction.song_id,
    actionType: interaction.action_type,
    sessionId: interaction.session_id || null,
    createdAt: interaction.created_at,
  };
};

/**
 * Transform array of models
 * @param {Array} items - Array of database models
 * @param {Function} transformer - Transformer function
 * @returns {Array} Transformed array
 */
const transformArray = (items, transformer) => {
  if (!Array.isArray(items)) return [];
  return items.map(item => transformer(item));
};

export {
  transformKeys,
  transformSong,
  transformPlaylist,
  transformUser,
  transformUserPreferences,
  transformUserInteraction,
  transformArray,
};
