/**
 * Database to Frontend Model Transformers
 * Converts snake_case database fields to camelCase for frontend consumption
 */

/**
 * Convert snake_case to camelCase
 * @param {string} str - Snake case string
 * @returns {string} Camel case string
 */
const snakeToCamel = (str) => {
  return str.replace(/_([a-z])/g, (match, letter) => letter.toUpperCase());
};

/**
 * Recursively transform object keys from snake_case to camelCase
 * @param {Object|Array} obj - Object or array to transform
 * @returns {Object|Array} Transformed object/array
 */
const transformKeys = (obj) => {
  if (Array.isArray(obj)) {
    return obj.map(item => transformKeys(item));
  }
  
  if (obj !== null && typeof obj === 'object' && !(obj instanceof Date)) {
    return Object.keys(obj).reduce((acc, key) => {
      const camelKey = snakeToCamel(key);
      acc[camelKey] = transformKeys(obj[key]);
      return acc;
    }, {});
  }
  
  return obj;
};

/**
 * Transform Song model from database to frontend format
 * @param {Object} song - Song from database
 * @returns {Object} Transformed song
 */
const transformSong = (song) => {
  if (!song) return null;
  
  return {
    id: song.id,
    title: song.title,
    artist: song.artist,
    album: song.album,
    albumArtUrl: song.album_art_url || null,
    durationMs: song.duration_ms,
    r2Key: song.r2_key,
    fileSizes: song.file_sizes || {},
    playCount: song.play_count || 0,
    lastUpdated: song.last_updated,
    popularityScore: song.popularity_score || 0,
    createdAt: song.created_at,
    updatedAt: song.updated_at,
  };
};

/**
 * Transform Playlist model from database to frontend format
 * @param {Object} playlist - Playlist from database
 * @returns {Object} Transformed playlist
 */
const transformPlaylist = (playlist) => {
  if (!playlist) return null;
  
  return {
    id: playlist.id,
    name: playlist.name,
    description: playlist.description || null,
    userId: playlist.user_id,
    songIds: playlist.song_ids || [],
    autoGenerated: playlist.auto_generated || false,
    isPublic: playlist.is_public || false,
    createdAt: playlist.created_at,
    updatedAt: playlist.updated_at,
  };
};

/**
 * Transform User model from database to frontend format
 * @param {Object} user - User from database
 * @returns {Object} Transformed user
 */
const transformUser = (user) => {
  if (!user) return null;
  
  return {
    id: user.id,
    email: user.email,
    username: user.username || null,
    profileImageUrl: user.profile_image_url || null,
    createdAt: user.created_at,
    updatedAt: user.updated_at,
  };
};

/**
 * Transform User Preferences model from database to frontend format
 * @param {Object} prefs - User preferences from database
 * @returns {Object} Transformed preferences
 */
const transformUserPreferences = (prefs) => {
  if (!prefs) return null;
  
  return {
    userId: prefs.user_id,
    preferredQuality: prefs.preferred_quality || 'high',
    autoDownload: prefs.auto_download || false,
    downloadQuality: prefs.download_quality || 'medium',
    dataSaverMode: prefs.data_saver_mode || false,
    theme: prefs.theme || 'dark',
    createdAt: prefs.created_at,
    updatedAt: prefs.updated_at,
  };
};

/**
 * Transform User Interaction model from database to frontend format
 * @param {Object} interaction - User interaction from database
 * @returns {Object} Transformed interaction
 */
const transformUserInteraction = (interaction) => {
  if (!interaction) return null;
  
  return {
    id: interaction.id,
    userId: interaction.user_id,
    songId: interaction.song_id,
    actionType: interaction.action_type,
    sessionId: interaction.session_id || null,
    createdAt: interaction.created_at,
  };
};

/**
 * Transform array of models
 * @param {Array} items - Array of database models
 * @param {Function} transformer - Transformer function
 * @returns {Array} Transformed array
 */
const transformArray = (items, transformer) => {
  if (!Array.isArray(items)) return [];
  return items.map(item => transformer(item));
};

export {
  snakeToCamel,
  transformKeys,
  transformSong,
  transformPlaylist,
  transformUser,
  transformUserPreferences,
  transformUserInteraction,
  transformArray,
};
